config/routes.rb
Rails.application.routes.draw do
get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions
  resources :users

  get 'welcome/index'
  resources :articles
  resources :categories

   root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :users
	has_many :article_categories
	has_many :categories, through: :article_categories

	validates :title, presence: true
	validates :content, presence: true
	validates :categories, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
 has_secure_password
 has_many :articles
 validates_uniqueness_of :email
 validates :name, presence: true
 validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories

	def authorize
		redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end


  private
	def current_user
	 @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user


	def get_categories
	@categories = Category.all.order(:name)
	end

end

app/controllers/articles_controller.rb
 class ArticlesController < ApplicationController
   before_filter :authorize, only: [:new]
   
   def index 
   	@articles = Article.order(updated_at: :desc).limit(25)
   end

   def show
   	@article = Article.find(params[:id])
   end

   def new
   	@article = Article.new
   end

   def create
   	@article = Article.new(article_params)
   	if @article.save
   		redirect_to @article
   	else
   		render "new"
		end
	end

   def edit
      @article = Article.find(params[:id])
   end

   def update
      @article = Article.find(params[:id])
      if @article.update(article_params)
         redirect_to @article
      else
         render "new"
      end      
   end


private
 def article_params
   params.require(:article).permit(:title, :content, :category_ids => [])
 end

 end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all.order(name: :asc)
  end
  
  def show
  	@category = Category.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	 user = User.find_by_email(params[:email])
	 if user && user.authenticate(params[:password]) # get this for free from has_secure_password
	   session[:user_id] = user.id
	   redirect_to root_url, notice: "Logged in"
	 else
	   flash.now.alert = "Email or password is invalid"
	   render "new"
	 end
  end

  def destroy 
  	session[:user_id] = nil 
  	redirect_to root_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def new
   @user = User.new
 end

 def create
   @user = User.new(user_params)
   if @user.save
     session[:user_id] = @user.id
     redirect_to root_url, notice: "Thank you for signing up"
   else
     render "new"
   end
 end

 private 
   def user_params
     params.require(:user).permit(:email, :name, :password, :password_confirmation)
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@recent_articles = Article.order(updated_at: :desc).limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 <div class="control-group">
   <%= f.label :title %>
   <div class="controls">
     <%= f.text_field :title %>
   </div>
 </div>
 <div class="control-group">
   <%= f.label :content %>
   <div class="controls">
     <%= f.text_area :content, rows: "20", cols: "100" %>
   </div>
 </div>

 <div class='category-control'>
   <%= f.label 'File under at least one category' %>
   <% Category.all.order(name: :asc).each do |category| %>
     <div>
       <%= check_box_tag "article[category_ids][]", category.id %>
       <%= category.name %>
     </div>
   <% end %>
 </div>

 <div class="form-actions">
   <%= f.submit nil %>
   <%= link_to 'Cancel', articles_path %>
 </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Your Article</h1>
<% if @article.errors.any? %>
<div class="error_messages">
   <h2>You're missing some fields</h2>
   <ul>
     <% @article.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

<!-- How 'new article' does it -->
<%= render :partial => 'form' %>

<!-- How Website One does it -->
<!-- <%= render 'form', article: @article %> -->

app/views/articles/index.html.erb
<h1>This is the index view for Articles</h1>
<% @articles.each do |article| %>
 <div>
   <h3><%= link_to article.title, article %></h3>
         <p>Published on <%= article.created_at.strftime('%b %d, %Y') %></p>
   <p>Filed under: <% article.categories.each do |category| %>
                     <%= category.name %>&nbsp;
                   <% end %>
   </p>
   <p><%= truncate(article.content, length: 200) %></p>
 </div>
<% end %>

app/views/articles/new.html.erb
<h1>Write and Publish a New Article</h1>
<% if @article.errors.any? %>
<div class="error_messages">
   <h2>You're missing some fields</h2>
   <ul>
     <% @article.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<h1>This is the show view for Articles</h1>

<div>
<h1><%= @article.title %></h1>
<p>Published <%= @article.created_at.strftime('%b %d, %Y') %></p>
<p>Filed under: <% @article.categories.each do |category| %>
  <%= category.name %>&nbsp;<% end %>
</p>
<div><%= @article.content %></div>
</div>

app/views/categories/index.html.erb
<h1>This is the index view for Categories</h1>

	<% @categories.each do |category| %>
	 <h3><%= link_to category.name, category %></h3>
	<% end %>

app/views/categories/show.html.erb
<h1>This is the show view for Categories</h1>


<div>
<h1><%= @category.name %></h1>
<% @category.articles.order(updated_at: :desc).each do |article| %>
 <p>  <h3><%= link_to article.title, article %></h3><% end %>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">	


	<!-- navigation bar -->
	<div class="navbar navbar-fixed-top">
	 <div class="navbar-inner">
	   <div class="container">
	     <%= link_to "Wikiful", root_path, :class => "brand" %>
		<div class='session-controls'> 
		<% if current_user %>
		  <%= link_to "Log Out", logout_path, :class => 'btn btn-primary btn-mini' %>
		  Logged in as <%= current_user.email %>.
		<% else %>
		  <div class="btn-group">
		    <%= link_to "Sign Up", signup_path, :class => "btn btn-mini" %>
		    <%= link_to "Log In", login_path, :class => "btn btn-mini" %>
		  </div>
		<% end %>
		</div>
	   </div>
	 </div>
	</div>
	<div class="row">
	 <div class="span4">
	   <% flash.each do |name, msg| %>
	     <%= content_tag :div, msg, id: "flash_#{name}" %>
	   <% end %>
	 </div>
	</div>
	  <div class="row">
		  <div class="col-md-9"><%= yield %></div> 
	  
		  <div class="col-md-3 sidebar">
			  	 <div class="my-wiki-site">
	  	 	        <h4>My Wikiful</h4>
	  	 	     </div>
	  	<ul>
          <li><%= link_to "Write a Wiki", new_article_path %></li>
        </ul>
	  	  </div>
	  	  <div class="categories-sidebar">
	  	  </div>
	  	  <h4>Categories</h4>
	  	   <ul>
              <% @categories.each do |category| %>
                <li><%= link_to category.name, category %></li>
              <% end %>



	  </div>
</div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
 <% if @user.errors.any? %>
   <div class="error_messages">
     <h2>Form is invalid</h2>
     <ul>
       <% @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
 <div class='field'>
   <%= f.label :name %>
   <%= f.text_field :name %> 
 </div>
 <div class='field'>
   <%= f.label :email %>
   <%= f.text_field :email %> 
 </div>
 <div class='field'>
   <%= f.label :password %>
   <%= f.password_field :password %> 
 </div>
 <div class='field'>
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation %> 
 </div>
 <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
	<% @recent_articles.each do |article| %>
	 <h3><%= link_to article.title, article %></h3>
	 <p><%= truncate(article.content, length: 200) %></p>
	 <% end %>